export const LOCATION_QUERY_TYPE_CITY = 'CITY';
export const LOCATION_QUERY_TYPE_POSTAL_CODE = 'POSTAL_CODE';
export const FORECAST_TYPE_DAILY = 'DAILY';
export const FORECAST_TYPE_HOURLY = 'HOURLY';
export const FORECAST_TYPE_WEEKLY = 'WEEKLY';
